---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ligabasq/public_html/wp-content/themes/liga-basket-chile
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R wp-content/themes/liga-basket-chile/. $DEPLOYPATH
